CREATE TABLE vehicles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  vin VARCHAR(20) NOT NULL UNIQUE,
  make VARCHAR(50) NOT NULL,
  model VARCHAR(50) NOT NULL,
  year SMALLINT NOT NULL,
  plates VARCHAR(20) NOT NULL,
  color VARCHAR(30) NOT NULL DEFAULT '',
  engine VARCHAR(50) NOT NULL DEFAULT '',
  transmission VARCHAR(30) NOT NULL DEFAULT '',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
